name: inpo_mobile_app
description: A multi-feature Flutter app for smart piggy bank

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 9.2.0
  injectable: 2.7.1+4
  flutter_bloc: 9.1.1
  equatable: 2.0.8
  stream_transform: 2.1.1
  dio: 5.9.0
  html: 0.15.6
  go_router: 17.0.1
  intl: any
  remove_markdown: 0.0.2
  hive_ce: 2.18.0
  hive_ce_flutter: 2.3.4
  cached_network_image: 3.4.1
  url_launcher: 6.3.2
  flutter_dotenv: 6.0.0
  flutter_screenutil: 5.9.3
  responsive_framework: 1.5.1
  logger: 2.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 9.0.0
  hive_ce_generator: 1.11.0
  injectable_generator: 2.12.0
  build_runner: 2.10.5
  bloc_lint: 0.3.6

flutter:
  uses-material-design: true

  fonts:
    - family: Onder
      fonts:
        - asset: assets/fonts/onder/Onder_Regular.ttf
          weight: 400
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Regular.otf
          weight: 400


  assets:
     - assets/images
     - .env
