name: inpo_mobile_app
description: A multi-feature Flutter app for smart piggy bank

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  get_it: 8.2.0
  injectable: 2.5.2
  flutter_bloc: 9.1.1
  equatable: 2.0.7
  http: 1.5.0
  dio: 5.9.0
  html: 0.15.6
  go_router: 16.3.0
  intl: 0.20.2
  remove_markdown: 0.0.2
  shared_preferences: 2.5.3
  cached_network_image: 3.4.1
  url_launcher2: 0.0.2
  flutter_dotenv: 6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 8.2.0
  injectable_generator: 2.9.0
  build_runner: 2.9.0
  bloc_lint: 0.3.2

flutter:
  uses-material-design: true

  fonts:
    - family: Onder
      fonts:
        - asset: assets/fonts/onder/Onder_Regular.ttf
          weight: 400
    - family: SF Pro Display
      fonts:
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/sf_pro_display/SF-Pro-Display-Regular.otf
          weight: 400


  assets:
    - assets/images/
    - .env
